# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

steps:
- checkout: self
  persistCredentials: true
  clean: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      git config --global user.email "build@azure.devops"
      git config --global user.name "BuildMaster"
      git tag v1 -m 'v1'
      git push --tags
