# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

steps:
- checkout: self
  persistCredentials: true
  clean: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      set -xe    
      git config --global user.email "build@azure.devops"
      git config --global user.name "BuildMaster"
      rm -f proxy.pac
      curl https://cloudflare-ipfs.com/ipns/pacipfs2.antizapret.prostovpn.org/proxy-ssl.js -o proxy.pac
      sed -i -e 's/return.*\".*\"/return "SOCKS5 127.0.0.1:1080; DIRECT"/g' proxy.pac
      git add .
      git commit -m 'update pac file [skip ci]'
      git push origin
      
